"""
Interpretations du Tarot de Marseille - Tirage en Croix
Chaque arcane a une interpretation selon sa position dans la croix
"""

# Positions du tirage en croix:
# 1. Centre: La situation presente / Le consultant
# 2. Gauche (Croix): Les obstacles / Ce qui s'oppose
# 3. Droite: Le conseil / Ce qui aide  
# 4. Haut: L'aboutissement / Le futur proche
# 5. Bas: La synthese / Le fondement cache

INTERPRETATIONS_CROIX = {
    0: {  # Le Mat
        "nom": "Le Mat",
        "mots_cles": "Liberte, depart, spontaneite, folie sacree",
        "description": "Le Mat est le voyageur eternel, l'ame libre qui n'a pas peur de l'inconnu. Il porte en lui le potentiel de tous les possibles. Sans numero, il echappe a tout systeme et represente la liberte absolue.",
        "centre": "Vous etes a un tournant decisif. Le Mat au centre indique une periode de transition majeure. Vous ressentez un appel irresistible vers l'inconnu. C'est le moment de faire confiance a la vie et de vous laisser porter par votre instinct. Quelque chose de nouveau demande a naitre en vous.",
        "obstacle": "Votre besoin de liberte et votre nature impulsive creent des turbulences. Vous fuyez peut-etre une situation au lieu de l'affronter. L'insouciance devient un obstacle quand elle vous empeche de voir les consequences de vos actes. Attention a ne pas bruler les ponts derriere vous.",
        "conseil": "Osez le saut dans l'inconnu. Le Mat vous conseille de lacher les amarres et de faire confiance au chemin. Ne planifiez pas tout, laissez la spontaneite vous guider. C'est en acceptant de ne pas tout controler que vous trouverez votre voie veritable.",
        "futur": "Un nouveau depart se profile a l'horizon. Un voyage, un demenagement ou un changement radical de direction est en preparation. Vous allez vivre une experience qui transformera votre vision du monde. Preparez-vous a l'inattendu.",
        "synthese": "Au plus profond de vous, il y a un desir ardent de liberte et d'aventure. Votre ame aspire a se liberer des contraintes et des conventions. Cette quete de liberte est le moteur cache de votre situation actuelle.",
    },
    1: {  # Le Bateleur
        "nom": "Le Bateleur",
        "mots_cles": "Creation, habilete, debut, potentiel",
        "description": "Le Bateleur est le magicien createur. Devant lui, tous les outils sont disposes. Il represente le commencement conscient, la volonte de creer et la maitrise des elements. C'est l'arcane du potentiel illimite.",
        "centre": "Vous avez tous les atouts en main pour reussir. Le Bateleur au centre revele que vous possedez les competences, les ressources et l'intelligence necessaires. C'est le moment d'agir avec confiance et creativite. Un nouveau projet ou une nouvelle phase de vie commence.",
        "obstacle": "Vous dispersez votre energie dans trop de directions. Le Bateleur en obstacle montre une tendance a la manipulation ou a la superficialite. Vous jongleza avec trop de choses a la fois et risquez de ne rien mener a bien. Concentrez-vous.",
        "conseil": "Utilisez votre creativite et votre intelligence. Le Bateleur vous invite a prendre l'initiative et a demarrer ce projet que vous avez en tete. Faites confiance a vos capacites. C'est en agissant que vous apprendrez.",
        "futur": "Un nouveau commencement prometteur se dessine. Vous allez trouver les ressources et l'inspiration pour lancer quelque chose d'important. Les prochaines semaines seront placees sous le signe de la creation et de l'action.",
        "synthese": "Votre fondation est faite de talent brut et de potentiel inexploite. Vous avez en vous bien plus de ressources que vous ne le pensez. La cle est d'oser les utiliser.",
    },
    2: {  # La Papesse
        "nom": "La Papesse",
        "mots_cles": "Intuition, secret, sagesse, patience",
        "description": "La Papesse est la gardienne des mysteres. Assise entre deux piliers, elle tient le livre de la connaissance sacree. Elle represente l'intuition profonde, la sagesse interieure et les verites qui se revelent dans le silence.",
        "centre": "Une periode d'introspection et de reflexion est necessaire. La Papesse au centre indique que la reponse que vous cherchez est deja en vous. Faites silence, meditez, ecoutez votre voix interieure. Un secret ou une verite cachee est sur le point de se reveler.",
        "obstacle": "Le silence et le retrait deviennent excessifs. Vous vous isolez trop ou refusez de communiquer. Des secrets non dits empoisonnent la situation. La passivite et l'indecision vous freinent. Il est temps de sortir de l'ombre.",
        "conseil": "Faites confiance a votre intuition. La Papesse vous dit de prendre du recul, de ne pas agir dans la precipitation. Etudiez, observez, meditez. Les reponses viendront naturellement quand vous serez pret(e) a les recevoir.",
        "futur": "Une revelation importante approche. Un savoir cache va emerger, peut-etre a travers un reve, une rencontre ou une decouverte inattendue. Votre intuition sera particulierement aiguisee dans les semaines a venir.",
        "synthese": "Votre fondation repose sur une sagesse interieure profonde. Meme si vous n'en etes pas toujours conscient(e), une guidance subtile vous accompagne depuis toujours.",
    },
    3: {  # L'Imperatrice
        "nom": "L'Imperatrice",
        "mots_cles": "Abondance, fertilite, creativite, sensualite",
        "description": "L'Imperatrice est la grande mere creatrice. Elle incarne l'abondance naturelle, la fertilite sous toutes ses formes et le pouvoir de donner la vie. Elle represente la creativite debordante et la connexion a la nature.",
        "centre": "Une periode d'abondance et de creativite s'ouvre a vous. L'Imperatrice au centre annonce la fecondite de vos projets. Que ce soit dans le domaine amoureux, professionnel ou creatif, quelque chose est en train de germer et de croitre.",
        "obstacle": "L'exces de confort ou la complaisance vous freinent. Vous vous laissez peut-etre aller a la facilite ou a la dependance affective. La possessivite ou l'etouffement menacent une relation. Retrouvez votre equilibre.",
        "conseil": "Nourrissez vos projets avec amour et patience. L'Imperatrice vous invite a vous connecter a votre creativite et a prendre soin de ce qui est en train de naitre. Faites confiance au processus naturel de croissance.",
        "futur": "L'abondance arrive. Un projet va porter ses fruits, une relation va s'epanouir ou une opportunite creative va se presenter. La periode qui vient sera fertile et genereuse.",
        "synthese": "Votre fondation est nourriciere et fertile. Vous avez la capacite innee de creer, de nourrir et de faire grandir tout ce que vous touchez.",
    },
    4: {  # L'Empereur
        "nom": "L'Empereur",
        "mots_cles": "Autorite, structure, stabilite, pouvoir",
        "description": "L'Empereur est le batisseur et le protecteur. Assis sur son trone de pierre, il incarne l'autorite naturelle, la structure et la capacite a construire des fondations solides. Il represente la maitrise du monde materiel.",
        "centre": "Vous etes appele(e) a prendre le controle de votre vie. L'Empereur au centre indique un besoin de structure, d'organisation et d'autorite. C'est le moment d'affirmer votre pouvoir personnel et de construire quelque chose de durable.",
        "obstacle": "La rigidite et le besoin de controle vous empechent d'avancer. Vous etes trop autoritaire ou trop attache(e) aux regles. L'inflexibilite etouffe la creativite et la spontaneite. Apprenez a lacher prise sur le controle.",
        "conseil": "Structurez votre approche. L'Empereur vous conseille d'etre methodique, organise et disciplin(e). Etablissez des regles claires, des objectifs precis et tenez-vous-y. La reussite passe par la perseverance.",
        "futur": "Une position de pouvoir ou de responsabilite vous attend. Vous allez etre amene(e) a diriger, organiser ou structurer quelque chose d'important. Votre autorite naturelle sera reconnue.",
        "synthese": "Votre fondation est solide comme le roc. Vous avez une capacite innee a construire et a proteger. Cette force est votre ancre dans les tempetes.",
    },
    5: {  # Le Pape
        "nom": "Le Pape",
        "mots_cles": "Sagesse, enseignement, tradition, guidance",
        "description": "Le Pape est le grand maitre spirituel. Il transmet la connaissance sacree et fait le pont entre le divin et l'humain. Il represente la sagesse accumulee, l'enseignement et la guidance bienveillante.",
        "centre": "Vous avez besoin de guidance ou vous etes appele(e) a guider les autres. Le Pape au centre indique une quete de sens et de sagesse. Un enseignement, un mentor ou une tradition spirituelle pourrait eclairer votre chemin.",
        "obstacle": "Le conformisme et le dogmatisme vous enferment. Vous suivez aveuglement les regles sans les questionner, ou vous imposez vos croyances aux autres. Liberez-vous des cadres trop rigides pour trouver votre propre verite.",
        "conseil": "Cherchez un guide ou devenez guide. Le Pape vous invite a transmettre ce que vous savez ou a chercher l'enseignement aupres de quelqu'un de sage. La tradition et l'experience ont beaucoup a vous offrir.",
        "futur": "Un enseignement majeur va transformer votre vision. Une rencontre avec un mentor, une formation ou une prise de conscience spirituelle est en preparation. Soyez ouvert(e) a l'apprentissage.",
        "synthese": "Votre fondation est spirituelle. Au plus profond de vous, il y a une quete de sens et de transcendance qui guide silencieusement toutes vos actions.",
    },
    6: {  # L'Amoureux
        "nom": "L'Amoureux",
        "mots_cles": "Choix, amour, union, epreuve du coeur",
        "description": "L'Amoureux est l'arcane du choix et de l'union. Sous le regard de l'ange, il doit choisir entre deux voies. Il represente les grands choix de la vie, l'amour veritable et l'epreuve du coeur.",
        "centre": "Un choix crucial se presente a vous. L'Amoureux au centre indique une decision importante qui engage votre coeur. Amour, partenariat ou dilemme moral, vous etes a la croisee des chemins. Ecoutez votre coeur autant que votre raison.",
        "obstacle": "L'indecision et les conflits emotionnels vous paralysent. Vous etes tiraille(e) entre deux options, deux personnes ou deux chemins. La peur de faire le mauvais choix vous empeche d'avancer. Il faut trancher.",
        "conseil": "Suivez votre coeur. L'Amoureux vous dit que la bonne decision est celle qui resonne avec votre etre profond. Ne choisissez pas par raison seule, ni par passion seule. Cherchez l'harmonie entre les deux.",
        "futur": "Une rencontre ou un choix amoureux majeur se profile. Dans les semaines a venir, votre vie affective va connaitre un tournant. Soyez pret(e) a ouvrir votre coeur.",
        "synthese": "Votre fondation est emotionnelle. L'amour, sous toutes ses formes, est le moteur secret de votre existence. Vos choix les plus importants sont toujours guides par le coeur.",
    },
    7: {  # Le Chariot
        "nom": "Le Chariot",
        "mots_cles": "Victoire, volonte, avancement, triomphe",
        "description": "Le Chariot est le triomphateur. Conduit par un prince courageux, tire par deux forces opposees qu'il maitrise, il avance inexorablement vers la victoire. Il represente la determination, le succes par la volonte.",
        "centre": "Vous etes en route vers la victoire. Le Chariot au centre indique un mouvement puissant vers vos objectifs. Votre determination est a son apogee. Rien ne peut vous arreter si vous maintenez le cap avec discipline et confiance.",
        "obstacle": "L'impatience et l'agressivite sabotent votre avancee. Vous forcez les choses au lieu de laisser le flux naturel operer. La course effrene vers le succes vous fait oublier l'essentiel. Ralentissez et reequilibrez vos forces.",
        "conseil": "Foncez avec determination mais maitrisez vos pulsions. Le Chariot vous dit d'avancer avec assurance tout en gardant le controle. Canalisez votre energie, ne la dispersez pas. La victoire est a portee de main.",
        "futur": "Le succes et la reconnaissance arrivent. Un aboutissement important est proche. Voyage, promotion, victoire personnelle ou professionnelle. Les efforts que vous avez fournis vont etre recompenses.",
        "synthese": "Votre fondation est la volonte pure. Quand vous decidez quelque chose, rien ne peut vous arreter. Cette force de caractere est votre plus grand atout.",
    },
    8: {  # La Justice
        "nom": "La Justice",
        "mots_cles": "Equilibre, verite, karma, decision",
        "description": "La Justice tient la balance et l'epee. Elle pese les actes et tranche avec impartialite. Elle represente la loi universelle de cause a effet, l'equilibre necessaire et la verite nue.",
        "centre": "Une question de justice ou d'equilibre est au coeur de votre situation. La Justice au centre demande honnetete et objectivite. Une decision importante doit etre prise avec discernement. Le karma est a l'oeuvre.",
        "obstacle": "L'injustice ou le desequilibre vous affecte. Vous subissez les consequences d'actions passees ou vous etes traite(e) injustement. Le manque d'objectivite ou les prejuges faussent votre jugement.",
        "conseil": "Soyez juste et honnete en tout. La Justice vous demande d'examiner la situation avec objectivite. Prenez vos responsabilites, corrigez les desequilibres et faites preuve d'integrite. La verite vous liberera.",
        "futur": "Un retablissement de l'equilibre est en cours. La justice va se faire, qu'elle soit legale, morale ou karmique. Ce qui vous est du va vous revenir. Faites confiance au processus.",
        "synthese": "Votre fondation est la quete d'equilibre. Au fond de vous, vous aspirez a l'harmonie, a la justice et a la verite. Ce sens moral profond guide vos choix.",
    },
    9: {  # L'Hermite
        "nom": "L'Hermite",
        "mots_cles": "Solitude, introspection, sagesse, recherche",
        "description": "L'Hermite marche seul avec sa lanterne, eclairant le chemin pas a pas. Il represente la quete interieure, la sagesse acquise par l'experience et la necessite de se retirer du monde pour trouver sa propre lumiere.",
        "centre": "Une periode de retrait et de reflexion est necessaire. L'Hermite au centre vous invite a ralentir, a vous eloigner du bruit du monde et a ecouter votre sagesse interieure. La solitude n'est pas une punition mais un cadeau.",
        "obstacle": "L'isolement excessif vous coupe des autres. Vous vous enfermez dans votre monde, refusant l'aide et le contact. La prudence excessive se transforme en paralysie. Il est temps de sortir de votre coquille.",
        "conseil": "Prenez le temps de la reflexion. L'Hermite vous dit de ne pas vous precipiter. Eloignez-vous des influences exterieures et cherchez la reponse en vous. La patience et la perseverance seront recompensees.",
        "futur": "Une periode de solitude feconde approche. Vous allez trouver la clarte a travers l'introspection. Un enseignement profond emerge de cette retraite interieure.",
        "synthese": "Votre fondation est la sagesse solitaire. Vous etes naturellement un(e) chercheur(euse) de verite. Cette quete interieure permanente est votre lumiere dans l'obscurite.",
    },
    10: {  # La Roue de Fortune
        "nom": "La Roue de Fortune",
        "mots_cles": "Destin, cycles, changement, chance",
        "description": "La Roue de Fortune tourne sans cesse. Certains montent, d'autres descendent. Elle represente les cycles inevitables de la vie, le destin, la chance et les retournements de situation imprevisibles.",
        "centre": "Un tournant majeur est en cours. La Roue au centre annonce un changement de cycle. Ce qui etait en haut peut descendre, et ce qui etait en bas peut monter. Acceptez les fluctuations de la vie avec sagesse.",
        "obstacle": "L'instabilite et les changements imprevisibles vous destabilisent. Vous resistez au mouvement naturel de la vie. L'attachement au statu quo vous empeche de profiter des nouvelles opportunites.",
        "conseil": "Embrassez le changement. La Roue vous dit que tout est cyclique. Si vous traversez une periode difficile, sachez qu'elle passera. Si tout va bien, profitez-en pleinement. Adaptez-vous au flux de la vie.",
        "futur": "Un retournement de situation favorable se prepare. La chance va tourner en votre faveur. Une opportunite inattendue va se presenter. Soyez pret(e) a saisir le moment.",
        "synthese": "Votre fondation est le mouvement perpetuel. Vous comprenez intuitivement que rien n'est permanent et que le changement est la seule constante. Cette sagesse vous rend resilient(e).",
    },
    11: {  # La Force
        "nom": "La Force",
        "mots_cles": "Courage, maitrise, douceur, puissance interieure",
        "description": "La Force dompte le lion non par la violence mais par la douceur et la maitrise de soi. Elle represente le courage interieur, la capacite a surmonter les epreuves par la patience et la force tranquille.",
        "centre": "Vous etes appele(e) a faire preuve de force interieure. La Force au centre indique que vous avez le courage et la resilience necessaires pour traverser cette epreuve. La vraie puissance n'est pas dans la force brute mais dans la maitrise de soi.",
        "obstacle": "Vos pulsions et vos instincts sont difficiles a controler. La colere, l'impatience ou les desirs excessifs sabotent vos efforts. Vous luttez contre vous-meme au lieu de vous maitriser avec douceur.",
        "conseil": "Domptez vos peurs avec douceur. La Force vous dit que vous etes plus fort(e) que vous ne le pensez. Approchez vos defis avec patience et determination calme. La douceur est plus puissante que la violence.",
        "futur": "Vous allez surmonter un obstacle majeur. Votre force interieure va etre mise a l'epreuve et vous en sortirez grandi(e). La victoire sera d'autant plus belle qu'elle aura ete obtenue avec grace.",
        "synthese": "Votre fondation est la force tranquille. Au fond de vous reside un courage immense que vous ne soupconnez pas toujours. C'est cette force silencieuse qui vous porte dans les moments difficiles.",
    },
    12: {  # Le Pendu
        "nom": "Le Pendu",
        "mots_cles": "Lacher-prise, sacrifice, suspension, illumination",
        "description": "Le Pendu est suspendu la tete en bas, mais son visage est serein et nimbe de lumiere. Il represente le sacrifice volontaire, le lacher-prise et la sagesse qui vient quand on voit le monde a l'envers.",
        "centre": "Vous etes dans une periode de suspension et de lacher-prise. Le Pendu au centre indique que vous devez arreter de lutter et accepter la situation telle qu'elle est. C'est en abandonnant le controle que vous trouverez la solution.",
        "obstacle": "Vous etes bloque(e) dans une situation d'impasse. Le sacrifice exige de vous est trop grand ou mal compris. Vous vous sentez piege(e) et impuissant(e). Changez de perspective pour voir la situation autrement.",
        "conseil": "Lacher prise. Le Pendu vous dit d'arreter de forcer les choses. Suspendez votre jugement, renversez votre point de vue. Ce qui semble un echec est peut-etre une benediction deguisee. La patience sera votre salut.",
        "futur": "Une revelation va venir de la ou vous ne l'attendez pas. Un sacrifice ou un renoncement va ouvrir une porte inattendue. La sagesse acquise dans l'epreuve sera votre plus grand tresor.",
        "synthese": "Votre fondation est le lacher-prise. Votre ame sait que les plus grandes revelations viennent quand on cesse de chercher. Cette capacite a vous abandonner au flux de la vie est votre force secrete.",
    },
    13: {  # L'Arcane sans Nom
        "nom": "L'Arcane sans Nom",
        "mots_cles": "Transformation, fin, renaissance, mutation",
        "description": "L'Arcane sans Nom est la grande faucheuse, mais elle ne represente pas la mort physique. Elle symbolise la fin necessaire d'un cycle pour qu'un nouveau puisse commencer. Elle est la transformation radicale et inevitable.",
        "centre": "Une transformation profonde est en cours. L'Arcane sans Nom au centre annonce la fin d'un chapitre et le debut d'un autre. Quelque chose doit mourir pour que le nouveau puisse naitre. Acceptez cette metamorphose.",
        "obstacle": "Vous resistez au changement necessaire. La peur de perdre ce que vous avez vous empeche d'evoluer. Vous vous accrochez a ce qui est mort. Laissez partir ce qui ne vous sert plus.",
        "conseil": "Acceptez la fin pour accueillir le renouveau. L'Arcane sans Nom vous dit que la destruction fait partie de la creation. Faites le deuil de l'ancien pour faire place au nouveau. La transformation est un cadeau.",
        "futur": "Une fin definitive approche, suivie d'une renaissance. Un aspect de votre vie va se transformer radicalement. N'ayez pas peur, ce qui vient apres sera meilleur que ce qui existait avant.",
        "synthese": "Votre fondation est la capacite de transformation. Vous avez deja traverse de nombreuses morts symboliques et vous en etes toujours ressorti(e) plus fort(e). Cette resilience est votre superpouvoir.",
    },
    14: {  # Temperance
        "nom": "Temperance",
        "mots_cles": "Equilibre, harmonie, patience, guerison",
        "description": "Temperance est l'ange guerisseur qui verse l'eau entre deux coupes, melant les contraires avec grace. Elle represente l'equilibre, la moderation, la guerison et la patience necessaire a l'harmonie.",
        "centre": "L'equilibre et l'harmonie sont au coeur de votre situation. Temperance au centre indique un besoin de moderation et de patience. Vous etes dans un processus de guerison ou de reconciliation. Laissez le temps faire son oeuvre.",
        "obstacle": "L'exces et l'impatience perturbent votre equilibre. Vous allez trop vite ou pas assez. Le manque de moderation dans vos actions ou vos emotions cree du chaos. Retrouvez la mesure.",
        "conseil": "Cultivez la patience et l'equilibre. Temperance vous invite a trouver le juste milieu en toute chose. Melangez le coeur et la raison, l'action et la reflexion. La guerison prend du temps.",
        "futur": "L'harmonie va se retablir progressivement. Une guerison emotionnelle ou physique est en cours. Les tensions vont s'apaiser et un nouvel equilibre va se creer naturellement.",
        "synthese": "Votre fondation est l'harmonie. Au plus profond de vous, il y a un artisan de paix qui cherche toujours l'equilibre entre les forces opposees. Cette qualite est votre don de guerison.",
    },
    15: {  # Le Diable
        "nom": "Le Diable",
        "mots_cles": "Tentation, attachement, passion, liberation",
        "description": "Le Diable est l'arcane des passions et des attachements. Il represente les chaines que nous nous imposons, les tentations qui nous lient et les pulsions qui nous controlent. Mais il est aussi la porte vers la liberation.",
        "centre": "Des attachements ou des passions dominent votre situation. Le Diable au centre revele des liens toxiques, des addictions ou des desirs incontroles. Vous etes peut-etre enchaine(e) a quelque chose ou quelqu'un. La prise de conscience est le premier pas vers la liberation.",
        "obstacle": "Les tentations et les dependances vous tirent vers le bas. Vous etes prisonnier(e) d'une situation, d'une relation ou d'un comportement qui vous nuit. Les chaines sont plus psychologiques que reelles. Vous avez le pouvoir de vous liberer.",
        "conseil": "Confrontez vos ombres. Le Diable vous dit de regarder en face ce qui vous enchaine. Acceptez votre part sombre sans la juger. C'est en reconnaissant vos chaines que vous pourrez les briser. La liberation passe par l'acceptation.",
        "futur": "Une liberation est en vue. Vous allez prendre conscience de ce qui vous enchaine et trouver la force de vous en liberer. La passion peut devenir une force creatrice si elle est maitrisee.",
        "synthese": "Votre fondation contient des ombres non resolues. Des peurs, des desirs ou des attachements anciens influencent vos choix actuels. Les reconnaitre est le chemin vers la liberte.",
    },
    16: {  # La Maison Dieu
        "nom": "La Maison Dieu",
        "mots_cles": "Revelation, choc, destruction, verite",
        "description": "La Maison Dieu est la tour frappee par la foudre. Elle represente l'illumination soudaine, la destruction des fausses structures et la revelation brutale de la verite. C'est un choc necessaire a la reconstruction.",
        "centre": "Un bouleversement majeur secoue votre vie. La Maison Dieu au centre annonce un evenement choc qui detruit les fausses certitudes. C'est douloureux mais necessaire. Des structures artificielles s'effondrent pour reveler la verite.",
        "obstacle": "Un choc ou une revelation brutale vous destabilise. Les fondations sur lesquelles vous aviez construit s'averent fragiles. L'orgueil precede la chute. Ce qui semblait solide peut s'ecrouler du jour au lendemain.",
        "conseil": "Acceptez la destruction pour mieux reconstruire. La Maison Dieu vous dit que les structures qui s'effondrent devaient tomber. Ne resistez pas a la foudre, elle eclaire autant qu'elle detruit. La verite peut blesser mais elle libere.",
        "futur": "Un evenement inattendu va changer la donne. Preparez-vous a un bouleversement qui, bien que destabilisant, sera liberateur a long terme. La reconstruction sera plus solide que l'original.",
        "synthese": "Votre fondation a besoin d'etre renovee. Des verites enfouies demandent a eclater au grand jour. Ce processus de destruction/reconstruction est necessaire a votre evolution.",
    },
    17: {  # L'Etoile
        "nom": "L'Etoile",
        "mots_cles": "Espoir, inspiration, serenite, guidage celeste",
        "description": "L'Etoile brille dans la nuit apres la tempete de la Maison Dieu. Elle represente l'espoir renove, l'inspiration divine, la serenite retrouvee et la connexion avec le cosmos. C'est la lumiere qui guide dans l'obscurite.",
        "centre": "L'espoir et l'inspiration illuminent votre situation. L'Etoile au centre est un message profondement positif. Apres une periode difficile, la lumiere revient. Vous etes guide(e) par une force bienveillante. Faites confiance a l'univers.",
        "obstacle": "Vous avez perdu espoir ou confiance en l'avenir. Le decouragement et le pessimisme obscurcissent votre vision. Vous ne voyez plus la lumiere au bout du tunnel. Relevez la tete, les etoiles brillent toujours.",
        "conseil": "Gardez la foi et suivez votre etoile. L'Etoile vous dit que vos reves sont valides et que l'univers conspire en votre faveur. Ouvrez-vous a l'inspiration et laissez-vous guider par votre etoile interieure.",
        "futur": "Une periode de grace et d'inspiration s'ouvre. Les choses vont s'eclaircir, l'espoir va renaitre et vous allez retrouver le chemin de la serenite. Un souhait profond pourrait se realiser.",
        "synthese": "Votre fondation est l'espoir eternel. Au fond de vous brille une lumiere que rien ne peut eteindre. Cette connexion avec le divin est votre boussole dans la nuit.",
    },
    18: {  # La Lune
        "nom": "La Lune",
        "mots_cles": "Illusions, inconscient, reves, peurs",
        "description": "La Lune eclaire le chemin entre deux tours, tandis qu'un chien et un loup hurlent et une ecrevisse emerge des profondeurs. Elle represente le monde des reves, des illusions, des peurs et de l'inconscient.",
        "centre": "Des illusions ou des peurs inconscientes troublent votre vision. La Lune au centre indique une periode de confusion ou les apparences sont trompeuses. Mefiez-vous des mirages et faites confiance a vos reves pour trouver la verite cachee.",
        "obstacle": "Les peurs, les angoisses et les illusions vous paralysent. Vous voyez des menaces la ou il n'y en a pas, ou vous ignorez des dangers reels. L'imagination debordante peut devenir toxique si elle n'est pas canalisee.",
        "conseil": "Explorez votre inconscient. La Lune vous invite a plonger dans vos reves et vos peurs pour y trouver des tresors caches. Tenez un journal de reves, meditez, explorez vos emotions profondes. La verite se cache derriere les illusions.",
        "futur": "Une periode de confusion emotionnelle approche mais elle est porteuse de revelations. Vos reves deviendront plus vifs et significatifs. Faites attention aux messages de votre inconscient.",
        "synthese": "Votre fondation est l'inconscient profond. Des memoires, des reves et des emotions cachees influencent votre vie de maniere invisible. Les explorer vous donnera une meilleure comprehension de vous-meme.",
    },
    19: {  # Le Soleil
        "nom": "Le Soleil",
        "mots_cles": "Joie, succes, vitalite, accomplissement",
        "description": "Le Soleil brille de tout son eclat sur deux enfants qui dansent. Il represente la joie pure, le succes eclatant, la vitalite et l'accomplissement. C'est l'arcane le plus positif du tarot.",
        "centre": "Le succes et la joie illuminent votre vie. Le Soleil au centre est le meilleur presage possible. Tout s'eclaircit, les obstacles se dissolvent et le bonheur rayonne. Profitez pleinement de cette benediction.",
        "obstacle": "L'exces de confiance ou l'aveuglement optimiste vous expose a des dangers que vous ne voyez pas. Vous negligez les details ou les avertissements car tout semble trop beau. Gardez un oeil ouvert meme dans la lumiere.",
        "conseil": "Rayonnez et partagez votre lumiere. Le Soleil vous dit de vivre pleinement, d'exprimer votre joie et de partager votre chaleur avec les autres. L'optimisme et la confiance sont vos meilleurs allies.",
        "futur": "Une periode de grand bonheur et de succes se profile. Les prochaines semaines seront lumineuses et fecondes. Un accomplissement majeur va vous combler de joie.",
        "synthese": "Votre fondation est la joie de vivre. Au plus profond de vous, il y a une lumiere inextinguible qui cherche a briller. Cette vitalite est votre cadeau au monde.",
    },
    20: {  # Le Jugement
        "nom": "Le Jugement",
        "mots_cles": "Renaissance, appel, liberation, bilan",
        "description": "L'ange sonne la trompette et les morts se levent de leurs tombeaux. Le Jugement represente la renaissance spirituelle, l'appel interieur, le bilan de vie et la liberation des fardeaux du passe.",
        "centre": "Un appel interieur puissant resonne en vous. Le Jugement au centre indique un moment de bilan et de renaissance. Le passe est revolu, un nouveau chapitre s'ouvre. Repondez a cet appel avec courage.",
        "obstacle": "Le poids du passe vous empeche de renaitre. Des regrets, des culpabilites ou des affaires non resolues vous retiennent. Le refus de faire le bilan vous condamne a repeter les memes erreurs.",
        "conseil": "Faites le bilan et liberez-vous du passe. Le Jugement vous appelle a faire la paix avec votre histoire. Pardonnez, acceptez et tournez la page. C'est en vous liberant du passe que vous pourrez renaitre.",
        "futur": "Une renaissance majeure approche. Vous allez vivre un renouveau profond qui touchera plusieurs aspects de votre vie. Un appel interieur va vous guider vers votre veritable vocation.",
        "synthese": "Votre fondation est la capacite de renaissance. Vous avez le don de vous reinventer apres chaque epreuve. Chaque fin est pour vous un nouveau commencement.",
    },
    21: {  # Le Monde
        "nom": "Le Monde",
        "mots_cles": "Accomplissement, plenitude, reussite, harmonie universelle",
        "description": "Le Monde est la danse cosmique de l'accomplissement. Entoure d'une couronne de laurier et des quatre elements, il represente la realisation totale, l'harmonie avec l'univers et la plenitude de l'etre.",
        "centre": "L'accomplissement et la plenitude sont au rendez-vous. Le Monde au centre est le couronnement d'un long parcours. Vous avez atteint ou vous etes sur le point d'atteindre un objectif majeur. Celebrez cette reussite.",
        "obstacle": "Vous refusez l'accomplissement ou ne vous sentez pas digne du succes. L'impossibilite de terminer ce que vous commencez ou la peur du vide apres l'aboutissement vous freine. Acceptez votre reussite.",
        "conseil": "Ouvrez-vous a la plenitude. Le Monde vous dit que vous meritez le succes et l'harmonie. Terminez ce que vous avez commence, celebrez vos victoires et ouvrez-vous a l'abondance universelle.",
        "futur": "L'accomplissement total est a portee de main. Tous les elements s'alignent pour que vous atteigniez votre objectif. Le voyage touche a sa fin heureuse. Un cycle se complete dans la joie.",
        "synthese": "Votre fondation est l'aspiration a la plenitude. Votre ame cherche l'harmonie universelle et la realisation de son plein potentiel. Ce desir d'accomplissement est le fil rouge de votre existence.",
    },
}
