"""
Interpretations du Tarot de Marseille - Tirage en Croix
Chaque arcane à une interpretation selon sa position dans la croix
"""

# Positions du tirage en croix:
# 1. Centre: La situation presente / Le consultant
# 2. Gauche (Croix): Les obstacles / Ce qui s'oppose
# 3. Droite: Le conseil / Ce qui aide  
# 4. Haut: L'aboutissement / Le futur proche
# 5. Bas: La synthese / Le fondement cache

INTERPRETATIONS_CROIX = {
    0: {  # Le Mat
        "nom": "Le Mat",
        "mots_cles": "Liberté, depart, spontanéité, folie sacrée",
        "description": "Le Mat est le voyageur éternel, l'ame libre qui n'a pas peur de l'inconnu. Il porte en lui le potentiel de tous les possibles. Sans numero, il échappe à tout système et représente la liberté absolue.",
        "centre": "Vous êtes à un tournant décisif. Le Mat au centre indique une période de transition majeure. Vous ressentez un appel irrésistible vers l'inconnu. C'est le moment de faire confiance à la vie et de vous laisser porter par votre instinct. Quelque chose de nouveau demande à naître en vous.",
        "obstacle": "Votre besoin de liberté et votre nature impulsive creent des turbulences. Vous fuyez peut-etre une situation au lieu de l'affronter. L'insouciance devient un obstacle quand elle vous empêche de voir les consequences de vos actes. Attention à ne pas bruler les ponts derriere vous.",
        "conseil": "Osez le saut dans l'inconnu. Le Mat vous conseille de lacher les amarres et de faire confiance au chemin. Ne planifiez pas tout, laissez la spontanéité vous guider. C'est en acceptant de ne pas tout contrôler que vous trouverez votre voie véritable.",
        "futur": "Un nouveau depart se profile à l'horizon. Un voyage, un déménagement ou un changement radical de direction est en préparation. Vous allez vivre une experience qui transformera votre vision du monde. Preparez-vous à l'inattendu.",
        "synthese": "Au plus profond de vous, il y à un désir ardent de liberté et d'aventure. Votre ame aspire à se libérer des contraintes et des conventions. Cette quete de liberté est le moteur cache de votre situation actuelle.",
    },
    1: {  # Le Bateleur
        "nom": "Le Bateleur",
        "mots_cles": "Creation, habileté, debut, potentiel",
        "description": "Le Bateleur est le magicien créateur. Devant lui, tous les outils sont disposes. Il représente le commencement conscient, la volonté de créer et la maîtrise des elements. C'est l'arcane du potentiel illimite.",
        "centre": "Vous avez tous les atouts en main pour réussir. Le Bateleur au centre révèle que vous possédez les compétences, les ressources et l'intelligence nécessaires. C'est le moment d'agir avec confiance et créativité. Un nouveau projet ou une nouvelle phase de vie commence.",
        "obstacle": "Vous dispersez votre énergie dans trop de directions. Le Bateleur en obstacle montre une tendance à la manipulation ou à la superficialité. Vous jongleza avec trop de choses à la fois et risquez de ne rien mener à bien. Concentrez-vous.",
        "conseil": "Utilisez votre créativité et votre intelligence. Le Bateleur vous invite à prendre l'initiative et à démarrer ce projet que vous avez en tete. Faites confiance à vos capacités. C'est en agissant que vous apprendrez.",
        "futur": "Un nouveau commencement prometteur se dessine. Vous allez trouver les ressources et l'inspiration pour lancer quelque chose d'important. Les prochaînes semaines seront placées sous le signe de la creation et de l'action.",
        "synthese": "Votre fondation est faite de talent brut et de potentiel inexploité. Vous avez en vous bien plus de ressources que vous ne le pensez. La cle est d'oser les utiliser.",
    },
    2: {  # La Papesse
        "nom": "La Papesse",
        "mots_cles": "Intuition, secret, sagesse, patience",
        "description": "La Papesse est la gardienne des mysteres. Assise entre deux piliers, elle tient le livre de la connaissance sacrée. Elle représente l'intuition profonde, la sagesse intérieure et les vérités qui se révèlent dans le silence.",
        "centre": "Une période d'introspection et de réflexion est nécessaire. La Papesse au centre indique que la réponse que vous cherchez est deja en vous. Faites silence, méditez, écoutez votre voix intérieure. Un secret ou une vérité cachee est sur le point de se révéler.",
        "obstacle": "Le silence et le retrait deviennent excèssifs. Vous vous isolez trop ou refusez de communiquer. Des secrets non dits empoisonnent la situation. La passivité et l'indécision vous freinent. Il est temps de sortir de l'ombre.",
        "conseil": "Faites confiance à votre intuition. La Papesse vous dit de prendre du recul, de ne pas agir dans la précipitation. Etudiez, observez, méditez. Les réponses viendront naturellement quand vous serez pret(e) à les recevoir.",
        "futur": "Une révélation importante approche. Un savoir cache va émerger, peut-etre à travers un reve, une rencontre ou une découverte inattendue. Votre intuition sera particulierement aiguisée dans les semaines à venir.",
        "synthese": "Votre fondation repose sur une sagesse intérieure profonde. Meme si vous n'en êtes pas toujours conscient(e), une guidance subtile vous accompagne depuis toujours.",
    },
    3: {  # L'Impératrice
        "nom": "L'Impératrice",
        "mots_cles": "Abondance, fertilité, créativité, sensualité",
        "description": "L'Impératrice est la grande mere créatrice. Elle incarne l'abondance naturelle, la fertilité sous toutes ses formes et le pouvoir de donner la vie. Elle représente la créativité débordante et la connexion à la nature.",
        "centre": "Une période d'abondance et de créativité s'ouvre à vous. L'Impératrice au centre annonce la fécondité de vos projets. Que ce soit dans le domaine amoureux, professionnel ou creatif, quelque chose est en train de germer et de croitre.",
        "obstacle": "L'excès de confort ou la complaisance vous freinent. Vous vous laissez peut-etre aller à la facilite ou à la dépendance affective. La possessivité ou l'étouffement menacent une relation. Retrouvez votre équilibre.",
        "conseil": "Nourrissez vos projets avec amour et patience. L'Impératrice vous invite à vous connecter à votre créativité et à prendre soin de ce qui est en train de naître. Faites confiance au processus naturel de croissance.",
        "futur": "L'abondance arrive. Un projet va porter ses fruits, une relation va s'épanouir ou une opportunite creative va se presenter. La période qui vient sera fertile et généreuse.",
        "synthese": "Votre fondation est nourriciere et fertile. Vous avez la capacité innee de créer, de nourrir et de faire grandir tout ce que vous touchez.",
    },
    4: {  # L'Empereur
        "nom": "L'Empereur",
        "mots_cles": "Autorite, structure, stabilité, pouvoir",
        "description": "L'Empereur est le batisseur et le protecteur. Assis sur son trone de pierre, il incarne l'autorité naturelle, la structure et la capacité à construire des fondations solides. Il représente la maîtrise du monde matériel.",
        "centre": "Vous êtes appele(e) à prendre le controle de votre vie. L'Empereur au centre indique un besoin de structure, d'organisation et d'autorité. C'est le moment d'affirmer votre pouvoir personnel et de construire quelque chose de durable.",
        "obstacle": "La rigidité et le besoin de controle vous empêchent d'avancer. Vous êtes trop autoritaire ou trop attache(e) aux règles. L'inflexibilite etouffe la créativité et la spontanéité. Apprenez à lacher prise sur le controle.",
        "conseil": "Structurez votre approche. L'Empereur vous conseille d'etre methodique, organise et disciplin(e). Etablissez des règles claires, des objectifs precis et tenez-vous-y. La réussite passe par la persévérance.",
        "futur": "Une position de pouvoir ou de responsabilite vous attend. Vous allez etre amene(e) à diriger, organiser ou structurer quelque chose d'important. Votre autorité naturelle sera reconnue.",
        "synthese": "Votre fondation est solide comme le roc. Vous avez une capacité innee à construire et à proteger. Cette force est votre ancre dans les tempetes.",
    },
    5: {  # Le Pape
        "nom": "Le Pape",
        "mots_cles": "Sagesse, enseignement, tradition, guidance",
        "description": "Le Pape est le grand maitre spirituel. Il transmet la connaissance sacrée et fait le pont entre le divin et l'humain. Il représente la sagesse accumulee, l'enseignement et la guidance bienveillante.",
        "centre": "Vous avez besoin de guidance ou vous êtes appele(e) à guider les autres. Le Pape au centre indique une quete de sens et de sagesse. Un enseignement, un mentor ou une tradition spirituelle pourrait éclairer votre chemin.",
        "obstacle": "Le conformisme et le dogmatisme vous enferment. Vous suivez aveuglément les règles sans les questionner, ou vous imposez vos croyances aux autres. Liberez-vous des cadres trop rigides pour trouver votre propre vérité.",
        "conseil": "Cherchez un guide ou devenez guide. Le Pape vous invite à transmettre ce que vous savez ou à chercher l'enseignement auprès de quelqu'un de sage. La tradition et l'experience ont beaucoup à vous offrir.",
        "futur": "Un enseignement majeur va transformer votre vision. Une rencontre avec un mentor, une formation ou une prise de conscience spirituelle est en préparation. Soyez ouvert(e) à l'apprentissage.",
        "synthese": "Votre fondation est spirituelle. Au plus profond de vous, il y à une quete de sens et de transcendance qui guide silencieusement toutes vos actions.",
    },
    6: {  # L'Amoureux
        "nom": "L'Amoureux",
        "mots_cles": "Choix, amour, union, épreuve du coeur",
        "description": "L'Amoureux est l'arcane du choix et de l'union. Sous le regard de l'ange, il doit choisir entre deux voies. Il représente les grands choix de la vie, l'amour véritable et l'épreuve du coeur.",
        "centre": "Un choix crucial se presente à vous. L'Amoureux au centre indique une décision importante qui engage votre coeur. Amour, partenariat ou dilemme moral, vous êtes à la croisee des chemins. Écoutez votre coeur autant que votre raison.",
        "obstacle": "L'indécision et les conflits emotionnels vous paralysent. Vous êtes tiraille(e) entre deux options, deux personnes ou deux chemins. La peur de faire le mauvais choix vous empêche d'avancer. Il faut trancher.",
        "conseil": "Suivez votre coeur. L'Amoureux vous dit que la bonne décision est celle qui resonne avec votre etre profond. Ne choisissez pas par raison seule, ni par passion seule. Cherchez l'harmonie entre les deux.",
        "futur": "Une rencontre ou un choix amoureux majeur se profile. Dans les semaines à venir, votre vie affective va connaître un tournant. Soyez pret(e) à ouvrir votre coeur.",
        "synthese": "Votre fondation est emotionnelle. L'amour, sous toutes ses formes, est le moteur secret de votre existence. Vos choix les plus importants sont toujours guides par le coeur.",
    },
    7: {  # Le Chariot
        "nom": "Le Chariot",
        "mots_cles": "Victoire, volonté, avancement, triomphe",
        "description": "Le Chariot est le triomphateur. Conduit par un prince courageux, tire par deux forces opposees qu'il maîtrise, il avance inexorablement vers la victoire. Il représente la determination, le succès par la volonté.",
        "centre": "Vous êtes en route vers la victoire. Le Chariot au centre indique un mouvement puissant vers vos objectifs. Votre determination est à son apogee. Rien ne peut vous arreter si vous maintenez le cap avec discipline et confiance.",
        "obstacle": "L'impatience et l'agressivite sabotent votre avancee. Vous forcez les choses au lieu de laisser le flux naturel operer. La course effrene vers le succès vous fait oublier l'essentiel. Ralentissez et reéquilibrez vos forces.",
        "conseil": "Foncez avec determination mais maîtrisez vos pulsions. Le Chariot vous dit d'avancer avec assurance tout en gardant le controle. Canalisez votre énergie, ne la dispersez pas. La victoire est à portee de main.",
        "futur": "Le succès et la reconnaissance arrivent. Un aboutissement important est proche. Voyage, promotion, victoire personnelle ou professionnelle. Les efforts que vous avez fournis vont etre recompenses.",
        "synthese": "Votre fondation est la volonté pure. Quand vous décidez quelque chose, rien ne peut vous arreter. Cette force de caractere est votre plus grand atout.",
    },
    8: {  # La Justice
        "nom": "La Justice",
        "mots_cles": "Équilibre, vérité, karma, décision",
        "description": "La Justice tient la balance et l'épée. Elle pese les actes et tranche avec impartialité. Elle représente la loi universelle de cause à effet, l'équilibre nécessaire et la vérité nue.",
        "centre": "Une question de justice ou d'équilibre est au coeur de votre situation. La Justice au centre demande honnetete et objectivité. Une décision importante doit etre prise avec discernement. Le karma est à l'oeuvre.",
        "obstacle": "L'injustice ou le deséquilibre vous affecte. Vous subissez les consequences d'actions passees ou vous êtes traite(e) injustement. Le manque d'objectivité ou les prejuges faussent votre jugement.",
        "conseil": "Soyez juste et honnete en tout. La Justice vous demande d'examiner la situation avec objectivité. Prenez vos responsabilités, corrigez les deséquilibres et faites preuve d'intégrité. La vérité vous libérera.",
        "futur": "Un retablissement de l'équilibre est en cours. La justice va se faire, qu'elle soit legale, morale ou karmique. Ce qui vous est du va vous revenir. Faites confiance au processus.",
        "synthese": "Votre fondation est la quete d'équilibre. Au fond de vous, vous aspirez à l'harmonie, à la justice et à la vérité. Ce sens moral profond guide vos choix.",
    },
    9: {  # L'Hermite
        "nom": "L'Hermite",
        "mots_cles": "Solitude, introspection, sagesse, recherche",
        "description": "L'Hermite marche seul avec sa lanterne, éclairant le chemin pas à pas. Il représente la quete intérieure, la sagesse acquise par l'experience et la necessite de se retirer du monde pour trouver sa propre lumière.",
        "centre": "Une période de retrait et de réflexion est nécessaire. L'Hermite au centre vous invite à ralentir, à vous éloigner du bruit du monde et à ecouter votre sagesse intérieure. La solitude n'est pas une punition mais un cadeau.",
        "obstacle": "L'isolement excèssif vous coupe des autres. Vous vous enfermez dans votre monde, refusant l'aide et le contact. La prudence excèssive se transforme en paralysie. Il est temps de sortir de votre coquille.",
        "conseil": "Prenez le temps de la réflexion. L'Hermite vous dit de ne pas vous précipiter. Éloignez-vous des influences extérieures et cherchez la réponse en vous. La patience et la persévérance seront récompensées.",
        "futur": "Une période de solitude féconde approche. Vous allez trouver la clarté à travers l'introspection. Un enseignement profond emerge de cette retraite intérieure.",
        "synthese": "Votre fondation est la sagesse solitaire. Vous êtes naturellement un(e) chercheur(euse) de vérité. Cette quete intérieure permanente est votre lumière dans l'obscurité.",
    },
    10: {  # La Roue de Fortune
        "nom": "La Roue de Fortune",
        "mots_cles": "Destin, cycles, changement, chance",
        "description": "La Roue de Fortune tourne sans cesse. Certains montent, d'autrès descendent. Elle représente les cycles inevitables de la vie, le destin, la chance et les retournements de situation imprevisibles.",
        "centre": "Un tournant majeur est en cours. La Roue au centre annonce un changement de cycle. Ce qui etait en haut peut descendre, et ce qui etait en bas peut monter. Acceptez les fluctuations de la vie avec sagesse.",
        "obstacle": "L'instabilité et les changements imprevisibles vous destabilisent. Vous resistez au mouvement naturel de la vie. L'attachement au statu quo vous empêche de profiter des nouvelles opportunites.",
        "conseil": "Embrassez le changement. La Roue vous dit que tout est cyclique. Si vous traversez une période difficile, sachez qu'elle passera. Si tout va bien, profitez-en pleinement. Adaptez-vous au flux de la vie.",
        "futur": "Un retournement de situation favorable se prepare. La chance va tourner en votre faveur. Une opportunite inattendue va se presenter. Soyez pret(e) à saisir le moment.",
        "synthese": "Votre fondation est le mouvement perpetuel. Vous comprenez intuitivement que rien n'est permanent et que le changement est la seule constante. Cette sagesse vous rend résilient(e).",
    },
    11: {  # La Force
        "nom": "La Force",
        "mots_cles": "Courage, maîtrise, douceur, puissance intérieure",
        "description": "La Force dompte le lion non par la violence mais par la douceur et la maîtrise de soi. Elle représente le courage intérieur, la capacité à surmonter les épreuves par la patience et la force tranquille.",
        "centre": "Vous êtes appele(e) à faire preuve de force intérieure. La Force au centre indique que vous avez le courage et la résilience nécessaires pour traverser cette épreuve. La vraie puissance n'est pas dans la force brute mais dans la maîtrise de soi.",
        "obstacle": "Vos pulsions et vos instincts sont difficiles à contrôler. La colere, l'impatience ou les désirs excèssifs sabotent vos efforts. Vous luttez contre vous-meme au lieu de vous maîtriser avec douceur.",
        "conseil": "Domptez vos peurs avec douceur. La Force vous dit que vous êtes plus fort(e) que vous ne le pensez. Approchez vos défis avec patience et determination calme. La douceur est plus puissante que la violence.",
        "futur": "Vous allez surmonter un obstacle majeur. Votre force intérieure va etre mise à l'épreuve et vous en sortirez grandi(e). La victoire sera d'autant plus belle qu'elle aura ete obtenue avec grace.",
        "synthese": "Votre fondation est la force tranquille. Au fond de vous reside un courage immense que vous ne soupconnez pas toujours. C'est cette force silencieuse qui vous porte dans les moments difficiles.",
    },
    12: {  # Le Pendu
        "nom": "Le Pendu",
        "mots_cles": "Lacher-prise, sacrifice, suspension, illumination",
        "description": "Le Pendu est suspendu la tete en bas, mais son visage est serein et nimbe de lumière. Il représente le sacrifice volontaire, le lacher-prise et la sagesse qui vient quand on voit le monde à l'envers.",
        "centre": "Vous êtes dans une période de suspension et de lacher-prise. Le Pendu au centre indique que vous devez arreter de lutter et accepter la situation telle qu'elle est. C'est en abandonnant le controle que vous trouverez la solution.",
        "obstacle": "Vous êtes bloque(e) dans une situation d'impasse. Le sacrifice exige de vous est trop grand ou mal compris. Vous vous sentez piege(e) et impuissant(e). Changez de perspective pour voir la situation autrement.",
        "conseil": "Lacher prise. Le Pendu vous dit d'arreter de forcer les choses. Suspendez votre jugement, renversez votre point de vue. Ce qui semble un echec est peut-etre une benediction deguisee. La patience sera votre salut.",
        "futur": "Une révélation va venir de la ou vous ne l'attendez pas. Un sacrifice ou un renoncement va ouvrir une porte inattendue. La sagesse acquise dans l'épreuve sera votre plus grand tresor.",
        "synthese": "Votre fondation est le lacher-prise. Votre ame sait que les plus grandes révélations viennent quand on cesse de chercher. Cette capacité à vous abandonner au flux de la vie est votre force secrete.",
    },
    13: {  # L'Arcane sans Nom
        "nom": "L'Arcane sans Nom",
        "mots_cles": "Transformation, fin, renaissance, mutation",
        "description": "L'Arcane sans Nom est la grande faucheuse, mais elle ne représente pas la mort physique. Elle symbolise la fin nécessaire d'un cycle pour qu'un nouveau puisse commencer. Elle est la transformation radicale et inevitable.",
        "centre": "Une transformation profonde est en cours. L'Arcane sans Nom au centre annonce la fin d'un chapitre et le debut d'un autre. Quelque chose doit mourir pour que le nouveau puisse naître. Acceptez cette metamorphose.",
        "obstacle": "Vous resistez au changement nécessaire. La peur de perdre ce que vous avez vous empêche d'evoluer. Vous vous accrochez à ce qui est mort. Laissez partir ce qui ne vous sert plus.",
        "conseil": "Acceptez la fin pour accueillir le renouveau. L'Arcane sans Nom vous dit que la destruction fait partie de la creation. Faites le deuil de l'ancien pour faire place au nouveau. La transformation est un cadeau.",
        "futur": "Une fin definitive approche, suivie d'une renaissance. Un aspect de votre vie va se transformer radicalement. N'ayez pas peur, ce qui vient après sera meilleur que ce qui existait avant.",
        "synthese": "Votre fondation est la capacité de transformation. Vous avez deja traverse de nombreuses morts symboliques et vous en êtes toujours ressorti(e) plus fort(e). Cette résilience est votre superpouvoir.",
    },
    14: {  # Temperance
        "nom": "Temperance",
        "mots_cles": "Équilibre, harmonie, patience, guérison",
        "description": "Temperance est l'ange guerisseur qui verse l'eau entre deux coupes, melant les contraires avec grace. Elle représente l'équilibre, la moderation, la guérison et la patience nécessaire à l'harmonie.",
        "centre": "L'équilibre et l'harmonie sont au coeur de votre situation. Temperance au centre indique un besoin de moderation et de patience. Vous êtes dans un processus de guérison ou de reconciliation. Laissez le temps faire son oeuvre.",
        "obstacle": "L'excès et l'impatience perturbent votre équilibre. Vous allez trop vite ou pas assez. Le manque de moderation dans vos actions ou vos emotions cree du chaos. Retrouvez la mesure.",
        "conseil": "Cultivez la patience et l'équilibre. Temperance vous invite à trouver le juste milieu en toute chose. Melangez le coeur et la raison, l'action et la réflexion. La guérison prend du temps.",
        "futur": "L'harmonie va se retablir progrèssivement. Une guérison emotionnelle ou physique est en cours. Les tensions vont s'apaiser et un nouvel équilibre va se créer naturellement.",
        "synthese": "Votre fondation est l'harmonie. Au plus profond de vous, il y à un artisan de paix qui cherche toujours l'équilibre entre les forces opposees. Cette qualite est votre don de guérison.",
    },
    15: {  # Le Diable
        "nom": "Le Diable",
        "mots_cles": "Tentation, attachement, passion, liberation",
        "description": "Le Diable est l'arcane des passions et des attachements. Il représente les chaînes que nous nous imposons, les tentations qui nous lient et les pulsions qui nous controlent. Mais il est aussi la porte vers la liberation.",
        "centre": "Des attachements ou des passions dominent votre situation. Le Diable au centre révèle des liens toxiques, des addictions ou des désirs incontroles. Vous êtes peut-etre enchaîne(e) à quelque chose ou quelqu'un. La prise de conscience est le premier pas vers la liberation.",
        "obstacle": "Les tentations et les dépendances vous tirent vers le bas. Vous êtes prisonnier(e) d'une situation, d'une relation ou d'un comportement qui vous nuit. Les chaînes sont plus psychologiques que reelles. Vous avez le pouvoir de vous libérer.",
        "conseil": "Confrontez vos ombres. Le Diable vous dit de regarder en face ce qui vous enchaîne. Acceptez votre part sombre sans la juger. C'est en reconnaissant vos chaînes que vous pourrez les briser. La liberation passe par l'acceptation.",
        "futur": "Une liberation est en vue. Vous allez prendre conscience de ce qui vous enchaîne et trouver la force de vous en libérer. La passion peut devenir une force créatrice si elle est maîtrisee.",
        "synthese": "Votre fondation contient des ombres non resolues. Des peurs, des désirs ou des attachements anciens influencent vos choix actuels. Les reconnaître est le chemin vers la liberté.",
    },
    16: {  # La Maison Dieu
        "nom": "La Maison Dieu",
        "mots_cles": "Révélation, choc, destruction, vérité",
        "description": "La Maison Dieu est la tour frappee par la foudre. Elle représente l'illumination soudaine, la destruction des fausses structures et la révélation brutale de la vérité. C'est un choc nécessaire à la reconstruction.",
        "centre": "Un bouleversement majeur secoue votre vie. La Maison Dieu au centre annonce un événement choc qui détruit les fausses certitudes. C'est douloureux mais nécessaire. Des structures artificielles s'effondrent pour révéler la vérité.",
        "obstacle": "Un choc ou une révélation brutale vous destabilise. Les fondations sur lesquelles vous aviez construit s'averent fragiles. L'orgueil precede la chute. Ce qui semblait solide peut s'ecrouler du jour au lendemain.",
        "conseil": "Acceptez la destruction pour mieux reconstruire. La Maison Dieu vous dit que les structures qui s'effondrent devaient tomber. Ne resistez pas à la foudre, elle éclaire autant qu'elle détruit. La vérité peut blesser mais elle libere.",
        "futur": "Un événement inattendu va changer la donne. Preparez-vous à un bouleversement qui, bien que destabilisant, sera liberateur à long terme. La reconstruction sera plus solide que l'original.",
        "synthese": "Votre fondation à besoin d'etre renovee. Des vérités enfouies demandent à eclater au grand jour. Ce processus de destruction/reconstruction est nécessaire à votre evolution.",
    },
    17: {  # L'Etoile
        "nom": "L'Etoile",
        "mots_cles": "Espoir, inspiration, sérénité, guidage celeste",
        "description": "L'Etoile brille dans la nuit après la tempete de la Maison Dieu. Elle représente l'espoir renove, l'inspiration divine, la sérénité retrouvee et la connexion avec le cosmos. C'est la lumière qui guide dans l'obscurité.",
        "centre": "L'espoir et l'inspiration illuminent votre situation. L'Etoile au centre est un message profondément positif. Après une période difficile, la lumière revient. Vous êtes guide(e) par une force bienveillante. Faites confiance à l'univers.",
        "obstacle": "Vous avez perdu espoir ou confiance en l'avenir. Le decouragement et le pessimisme obscurcissent votre vision. Vous ne voyez plus la lumière au bout du tunnel. Rélevez la tete, les etoiles brillent toujours.",
        "conseil": "Gardez la foi et suivez votre etoile. L'Etoile vous dit que vos rêves sont valides et que l'univers conspire en votre faveur. Ouvrez-vous à l'inspiration et laissez-vous guider par votre etoile intérieure.",
        "futur": "Une période de grace et d'inspiration s'ouvre. Les choses vont s'eclaircir, l'espoir va renaître et vous allez retrouver le chemin de la sérénité. Un souhait profond pourrait se réaliser.",
        "synthese": "Votre fondation est l'espoir éternel. Au fond de vous brille une lumière que rien ne peut eteindre. Cette connexion avec le divin est votre boussole dans la nuit.",
    },
    18: {  # La Lune
        "nom": "La Lune",
        "mots_cles": "Illusions, inconscient, rêves, peurs",
        "description": "La Lune éclaire le chemin entre deux tours, tandis qu'un chien et un loup hurlent et une ecrevisse emerge des profondeurs. Elle représente le monde des rêves, des illusions, des peurs et de l'inconscient.",
        "centre": "Des illusions ou des peurs inconscientes troublent votre vision. La Lune au centre indique une période de confusion ou les apparences sont trompeuses. Mefiez-vous des mirages et faites confiance à vos rêves pour trouver la vérité cachee.",
        "obstacle": "Les peurs, les angoisses et les illusions vous paralysent. Vous voyez des menaces la ou il n'y en à pas, ou vous ignorez des dangers reels. L'imagination débordante peut devenir toxique si elle n'est pas canalisee.",
        "conseil": "Explorez votre inconscient. La Lune vous invite à plonger dans vos rêves et vos peurs pour y trouver des tresors caches. Tenez un journal de rêves, méditez, explorez vos emotions profondes. La vérité se cache derriere les illusions.",
        "futur": "Une période de confusion emotionnelle approche mais elle est porteuse de révélations. Vos rêves deviendront plus vifs et significatifs. Faites attention aux messages de votre inconscient.",
        "synthese": "Votre fondation est l'inconscient profond. Des memoires, des rêves et des emotions cachees influencent votre vie de manière invisible. Les explorer vous donnera une meilleure comprehension de vous-meme.",
    },
    19: {  # Le Soleil
        "nom": "Le Soleil",
        "mots_cles": "Joie, succès, vitalite, accomplissement",
        "description": "Le Soleil brille de tout son eclat sur deux enfants qui dansent. Il représente la joie pure, le succès eclatant, la vitalite et l'accomplissement. C'est l'arcane le plus positif du tarot.",
        "centre": "Le succès et la joie illuminent votre vie. Le Soleil au centre est le meilleur presage possible. Tout s'eclaircit, les obstacles se dissolvent et le bonheur rayonne. Profitez pleinement de cette benediction.",
        "obstacle": "L'excès de confiance ou l'aveuglément optimiste vous expose à des dangers que vous ne voyez pas. Vous negligez les details ou les avertissements car tout semble trop beau. Gardez un oeil ouvert meme dans la lumière.",
        "conseil": "Rayonnez et partagez votre lumière. Le Soleil vous dit de vivre pleinement, d'exprimer votre joie et de partager votre chaleur avec les autres. L'optimisme et la confiance sont vos meilleurs allies.",
        "futur": "Une période de grand bonheur et de succès se profile. Les prochaînes semaines seront lumineuses et fecondes. Un accomplissement majeur va vous combler de joie.",
        "synthese": "Votre fondation est la joie de vivre. Au plus profond de vous, il y à une lumière inextinguible qui cherche à briller. Cette vitalite est votre cadeau au monde.",
    },
    20: {  # Le Jugement
        "nom": "Le Jugement",
        "mots_cles": "Renaissance, appel, liberation, bilan",
        "description": "L'ange sonne la trompette et les morts se levent de leurs tombeaux. Le Jugement représente la renaissance spirituelle, l'appel intérieur, le bilan de vie et la liberation des fardeaux du passe.",
        "centre": "Un appel intérieur puissant resonne en vous. Le Jugement au centre indique un moment de bilan et de renaissance. Le passe est revolu, un nouveau chapitre s'ouvre. Repondez à cet appel avec courage.",
        "obstacle": "Le poids du passe vous empêche de renaître. Des regrets, des culpabilites ou des affaires non resolues vous retiennent. Le refus de faire le bilan vous condamne à repeter les memes erreurs.",
        "conseil": "Faites le bilan et libérez-vous du passe. Le Jugement vous appelle à faire la paix avec votre histoire. Pardonnez, acceptez et tournez la page. C'est en vous liberant du passe que vous pourrez renaître.",
        "futur": "Une renaissance majeure approche. Vous allez vivre un renouveau profond qui touchera plusieurs aspects de votre vie. Un appel intérieur va vous guider vers votre véritable vocation.",
        "synthese": "Votre fondation est la capacité de renaissance. Vous avez le don de vous reinventer après chaque épreuve. Chaque fin est pour vous un nouveau commencement.",
    },
    21: {  # Le Monde
        "nom": "Le Monde",
        "mots_cles": "Accomplissement, plenitude, réussite, harmonie universelle",
        "description": "Le Monde est la danse cosmique de l'accomplissement. Entoure d'une couronne de laurier et des quatre elements, il représente la réalisation totale, l'harmonie avec l'univers et la plenitude de l'etre.",
        "centre": "L'accomplissement et la plenitude sont au rendez-vous. Le Monde au centre est le couronnement d'un long parcours. Vous avez atteint ou vous êtes sur le point d'atteindre un objectif majeur. Celebrez cette réussite.",
        "obstacle": "Vous refusez l'accomplissement ou ne vous sentez pas digne du succès. L'impossibilite de terminer ce que vous commencez ou la peur du vide après l'aboutissement vous freine. Acceptez votre réussite.",
        "conseil": "Ouvrez-vous à la plenitude. Le Monde vous dit que vous meritez le succès et l'harmonie. Terminez ce que vous avez commence, célébrez vos victoires et ouvrez-vous à l'abondance universelle.",
        "futur": "L'accomplissement total est à portee de main. Tous les elements s'alignent pour que vous atteigniez votre objectif. Le voyage touche à sa fin heureuse. Un cycle se complete dans la joie.",
        "synthese": "Votre fondation est l'aspiration à la plenitude. Votre ame cherche l'harmonie universelle et la réalisation de son plein potentiel. Ce désir d'accomplissement est le fil rouge de votre existence.",
    },
}
