services:
  mongodb:
    image: mongo:7
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - plume_network

  backend:
    build:
      context: .
      dockerfile: deploy/Dockerfile.backend
    restart: always
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=plume_astrale
      - CORS_ORIGINS=*
      - STRIPE_API_KEY=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
      - ASTROLOGY_API_USER_ID=649448
      - ASTROLOGY_API_KEY=fdc70a8227029d5e3f11ba9e495bb56995bb343a
      - ASTROLOGY_PDF_USER_ID=649448
      - ASTROLOGY_PDF_API_KEY=c520138ec226c81240e263e1034fdd53dfa71d23
    depends_on:
      - mongodb
    networks:
      - plume_network

  frontend:
    build:
      context: .
      dockerfile: deploy/Dockerfile.frontend
      args:
        - REACT_APP_BACKEND_URL=
    restart: always
    networks:
      - plume_network

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/lib/letsencrypt
    depends_on:
      - frontend
      - backend
    networks:
      - plume_network

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/lib/letsencrypt
    depends_on:
      - nginx

volumes:
  mongo_data:
  certbot_etc:
  certbot_var:

networks:
  plume_network:
    driver: bridge
